/***********************************************************************/
/*                                                                     */
/*  FILE        :62N.c                                                 */
/*  DATE        :Sat, Mar 26, 2016                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :RX62N                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.53).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/
                  


//#include "typedefine.h"
#ifdef __cplusplus
//#include <ios>                        // Remove the comment when you use ios
//_SINT ios_base::Init::init_cnt;       // Remove the comment when you use ios
#endif
#include "iodefine.h"
void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void main(void)
{
	HIT_hardwaresetup();      // 硬件初始化
	RSPI1.SPCR.BIT.SPE = 1;
	RSPI0.SPCR.BIT.SPE = 1;
	RSPI1.SPCMD0.BIT.SPB = 0X07;
	//HIT_par_initial();        //参数初始化 
	/***
	PORTE.DDR.BIT.B6 = 0X01;
	PORTE.DR.BIT.B6 = 0X00;
	PORTE.DDR.BIT.B7 = 0X01;
	PORTE.DR.BIT.B7 = 0X00; ***/
	while(1)
	{
		
	}
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
