extern char HIT_pos_count;
extern int HIT_position1_fb_16_int;
extern int HIT_new_angle_int;
extern float HIT_sita1;
extern float HIT_sita;
extern int HIT_virtual_ps_int_sec;
extern int HIT_virtual_ps_int;
extern unsigned short HIT_a_phase_sum;
extern int HIT_pos_org_int ;
extern float HIT_pos_org_f;
extern float HIT_WLw_org;
extern float HIT_wtwo;
extern float HIT_speedlpf;
extern int HIT_virtual_ps_int_err;
extern float HIT_virtual_ps_int_err_sum_f;
extern unsigned short HIT_filter_i;
extern int HIT_a_phase_filter[];